name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mruby-version:
          - "3.3.0"
          - "3.4.0"
          - "head"
    steps:
      - name: Checkout mrbgem repository
        uses: actions/checkout@v4
        with:
          path: mrbgem

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            bison \
            rake

      - name: Clone mruby
        run: |
          if [ "${{ matrix.mruby-version }}" = "head" ]; then
            git clone https://github.com/mruby/mruby.git
          else
            git clone --branch ${{ matrix.mruby-version }} --depth 1 https://github.com/mruby/mruby.git
          fi

      - name: Create build config
        run: |
          cat > build_config.rb << 'EOF'
          MRuby::Build.new do |conf|
            toolchain :gcc
            
            conf.enable_debug
            conf.enable_test
            
            # Add your mrbgem (adjust path as needed)
            conf.gem File.expand_path('mrbgem', __dir__)
            
            # Enable all warnings as errors for strict testing
            conf.cc.flags << '-Wall' << '-Werror'
            
            # Generate test executable
            conf.enable_test
          end
          EOF

      - name: Build mruby with mrbgem
        run: |
          cd mruby
          make clean
          MRUBY_CONFIG=../build_config.rb ruby ./minirake

      - name: Run mruby tests
        run: |
          cd mruby
          MRUBY_CONFIG=../build_config.rb ruby ./minirake test
